name: CI-CD-Pipeline-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "klymenok-flask-application-packedges"
  EB_APPLICATION_NAME       : "Flask"
  EB_ENVIROMENT_NAME        : "Flask-env-1"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"
  
on:
  push:
    branches:
      - main
  

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3
      
      - name: Create zip deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id       : ${{ secrets.AWS_ACCCES_KEY }}
          aws-secret-access-key-id: ${{ secrets.AWS_SECRET_KEY }}
          aws-region              : ${{ env.AWS_REGION_NAME }}
      
      - name: Copy deployment files to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
        
  cd_part:
     runs-on: ubuntu-latest
     needs: [ci_part]
     
     steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id       : ${{ secrets.AWS_ACCCES_KEY }}
            aws-secret-access-key-id: ${{ secrets.AWS_SECRET_KEY }}
            aws-region              : ${{ env.AWS_REGION_NAME }}
            
        - name: Create ElasticBeanstalk Application
          run : 
            aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}", S3key="${{ env.DEPLOY_PACKAGE_NAME }}" \
            --version-lable "Ver-${{ github.sha }}" \
            --description "CommitSHA-${{ github.sha }}"
            
        - name: Deploy ElasticBeanstalc Appication Version
          run : aws elacticbeanstalk update-enviroment
                --environment-name ${{ env.EB_ENVIROMENT_NAME }} \
                --version-lable "Ver-${{ github.sha }}"
                
        
       
     
