
name: CI-CD-Pipeline-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "klymenok-flask-application-packedges"
  EB_APPLICATION_NAME       : "Flask"
  EB_ENVIROMENT_NAME        : "Flask-env-1"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"

on:
  push:
    branches: 
      -master
  

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
      - uses: actions/checkout@v3
      
      - name: Create zip deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
